export const COURSES_GET_ALUMN_REQUEST = 'COURSES_GET_ALUMN_REQUEST';
export const COURSES_GET_ALUMN_SUCCESS = 'COURSES_GET_ALUMN_SUCCESS';
export const COURSES_GET_ALUMN_FAIL = 'COURSES_GET_ALUMN_FAIL';

export const COURSE_GET_ALUMN_REQUEST = 'COURSE_GET_ALUMN_REQUEST';
export const COURSE_GET_ALUMN_SUCCESS = 'COURSE_GET_ALUMN_SUCCESS';
export const COURSE_GET_ALUMN_FAIL = 'COURSE_GET_ALUMN_FAIL';